### ISSUE TITLE
Return work with multiple argument

### ISSUE THREAD

**Issue by MichJuffard** [lohhiiccc/Minishell#78]
➜  minishell git:(76-leaks-in-heredoc) ✗ ./minishell 
[🥚][/home/mjuffard/Rendu/minishell] Minichel$ return 1 0
[🐥][/home/mjuffard/Rendu/minishell] Minichel$ echo $?
1
[🥚][/home/mjuffard/Rendu/minishell] Minichel$ bash
mjuffard@z1r6p4: ~/Rendu/minishell$ return 1 0
bash: return: too many arguments
mjuffard@z1r6p4:  ~/Rendu/minishell$ echo $?
1
mjuffard@z1r6p4: ~/Rendu/minishell$

**Comment by lohhiiccc** [comment]
### the goal is not to have the same implementation as bash for the bash buildin
bash 'return' build-in terminates command line
